name: mappymatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - osmnx
  - geopandas
  - shapely
  - rtree
  - pyproj
  - pandas
  - numpy
  - matplotlib
  - folium
  - requests
  - pip
  - pytest
  
