name: mappymatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - folium
  - geopandas
  - matplotlib
  - numpy
  - osmnx
  - pandas
  - pip
  - pip:
      - .
  - pyproj
  - requests
  - rtree
  - shapely
