name: Build and Release Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/mappymatch/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build package
        run: |
          hatch build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
