name: Test only

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy isort types-requests
    - name: Run black
      if: always()
      run: black mappymatch tests --check